name: LinkedIn Post Scheduler

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
    - cron: "0 0-23/1 * * *" # Hourly (adjust as needed)
  workflow_dispatch:

jobs:
  post-to-linkedin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build
      - run: npm run post-to-linkedin
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}